### ISSUE TITLE
Compost by right-click?

### ISSUE THREAD

**Issue by derekantrican** [daenvil/more_compostable_items#1]
It seems the custom items are only supported by either hopper or dropping - not right-clicking the item on the composter. Is it possible to add this? I was convinced this datapack wasn't working until I went back to the page and saw that "right-clicking" with an item on the composter wasn't explicitly listed.

**Comment by daenvil** [comment]
Hi, this due to a short-coming of datapacks: it's very difficult (if not impossible) to reliably detect when the player right clicks with a generic item on their hand. You have a more detailed explanation at the readme: [#interacting-with-composters-by-hand](https://github.com/daenvil/more_compostable_items#interacting-with-composters-by-hand)

**Comment by Heroesflorian** [comment]
For anyone stumbling across this and wondering: 
I assume you could combine some sort of raycasting or fake-raycasting system (for the positioning / detecting aiming at composter) with consume-based right-click detection for non-block items, if you modify all relevant items to have a "dummy" consumable component (with "endless" consume duration) if they are not consumable by default already - which in turn might involve changing a fast amount of block loot tables, villager trading loot tables, as well as some other loot tables and potentially additional ticking functions checking for other ways to obtain such items; or constantly ticking functions permanently detecting and updating all non-default consumable items you want to be composted... and then there's the block items where consumable components triggering start of consumption on right-click would inherently conflict with the ability to place them as blocks in the world, thus most likely requiring further workarounds... so, ehh... yeah, not feasible nor desirable.

**Comment by daenvil** [comment]
yup, and when this datapack was originally made we didn't even have a way of setting items as consumable... Mojang did add the interaction entity some years ago, but it consumes interactions and so it makes it impossible to place blocks by looking at a composter. So yeah we still have no way of implementing custom interactions reliably and efficiently.
